### ISSUE TITLE
Steps Navigation Bar + Move Page Content 

### ISSUE THREAD

**Issue by sirkevinwang** [sirkevinwang/StageIQ#6]
<img width="242" alt="Screen Shot 2021-04-20 at 1 41 37 AM" src="https://user-images.githubusercontent.com/16371755/115343216-8df9b880-a179-11eb-9239-512479a211fa.png">

**Comment by sirkevinwang** [comment]
<img width="218" alt="Screen Shot 2021-04-20 at 1 39 27 AM" src="https://user-images.githubusercontent.com/16371755/115343043-3fe4b500-a179-11eb-85a5-6531c5c27db0.png">

**Comment by mattfang1999** [comment]
https://github.com/sirkevinwang/StageIQ/pull/32
